// @flow

// ------------------------------------
// Code generated by protoc-gen-flow
// source: ociobjectstorewatcher.proto
// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!
// ------------------------------------

declare type ActionRequest = {|
	resourceApplicationId: string;
	resourceUserId: string;
	resource: Resource;
|};

declare type ActionResponse = {|
	success: boolean;
|};

declare type Resource = {|
	kind: string;
|};
