// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ociobjectstorewatcher.proto

/*
Package ociobjectstorewatcherpb is a generated protocol buffer package.

It is generated from these files:
	ociobjectstorewatcher.proto

It has these top-level messages:
	ActionRequest
	ActionResponse
	Resource
*/
package ociobjectstorewatcherpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ActionRequest struct {
	ResourceApplicationId string    `protobuf:"bytes,1,opt,name=resourceApplicationId" json:"resourceApplicationId,omitempty"`
	ResourceUserId        string    `protobuf:"bytes,2,opt,name=resourceUserId" json:"resourceUserId,omitempty"`
	Resource              *Resource `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
}

func (m *ActionRequest) Reset()                    { *m = ActionRequest{} }
func (m *ActionRequest) String() string            { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()               {}
func (*ActionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ActionRequest) GetResourceApplicationId() string {
	if m != nil {
		return m.ResourceApplicationId
	}
	return ""
}

func (m *ActionRequest) GetResourceUserId() string {
	if m != nil {
		return m.ResourceUserId
	}
	return ""
}

func (m *ActionRequest) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type ActionResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ActionResponse) Reset()                    { *m = ActionResponse{} }
func (m *ActionResponse) String() string            { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()               {}
func (*ActionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ActionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Resource struct {
	Kind string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func init() {
	proto.RegisterType((*ActionRequest)(nil), "ociobjectstorewatcher.ActionRequest")
	proto.RegisterType((*ActionResponse)(nil), "ociobjectstorewatcher.ActionResponse")
	proto.RegisterType((*Resource)(nil), "ociobjectstorewatcher.Resource")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for OciObjectstoreWatcher service

type OciObjectstoreWatcherClient interface {
	Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type ociObjectstoreWatcherClient struct {
	cc *grpc.ClientConn
}

func NewOciObjectstoreWatcherClient(cc *grpc.ClientConn) OciObjectstoreWatcherClient {
	return &ociObjectstoreWatcherClient{cc}
}

func (c *ociObjectstoreWatcherClient) Action(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := grpc.Invoke(ctx, "/ociobjectstorewatcher.OciObjectstoreWatcher/Action", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for OciObjectstoreWatcher service

type OciObjectstoreWatcherServer interface {
	Action(context.Context, *ActionRequest) (*ActionResponse, error)
}

func RegisterOciObjectstoreWatcherServer(s *grpc.Server, srv OciObjectstoreWatcherServer) {
	s.RegisterService(&_OciObjectstoreWatcher_serviceDesc, srv)
}

func _OciObjectstoreWatcher_Action_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OciObjectstoreWatcherServer).Action(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ociobjectstorewatcher.OciObjectstoreWatcher/Action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OciObjectstoreWatcherServer).Action(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OciObjectstoreWatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ociobjectstorewatcher.OciObjectstoreWatcher",
	HandlerType: (*OciObjectstoreWatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Action",
			Handler:    _OciObjectstoreWatcher_Action_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ociobjectstorewatcher.proto",
}

func init() { proto.RegisterFile("ociobjectstorewatcher.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x4f, 0xce, 0xcc,
	0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0x29, 0x2e, 0xc9, 0x2f, 0x4a, 0x2d, 0x4f, 0x2c, 0x49, 0xce, 0x48,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc5, 0x2a, 0x29, 0x25, 0x93, 0x9e, 0x9f,
	0x9f, 0x9e, 0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9, 0x9f, 0x98, 0x97, 0x97, 0x5f, 0x92, 0x58, 0x92,
	0x99, 0x9f, 0x57, 0x0c, 0xd1, 0xa4, 0xb4, 0x8a, 0x91, 0x8b, 0xd7, 0x31, 0x19, 0x24, 0x12, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x64, 0xc2, 0x25, 0x5a, 0x94, 0x5a, 0x9c, 0x5f, 0x5a, 0x94,
	0x9c, 0xea, 0x58, 0x50, 0x90, 0x93, 0x99, 0x0c, 0x56, 0xef, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x19, 0x84, 0x5d, 0x52, 0x48, 0x8d, 0x8b, 0x0f, 0x26, 0x11, 0x5a, 0x9c, 0x5a, 0xe4, 0x99,
	0x22, 0xc1, 0x04, 0x56, 0x8e, 0x26, 0x2a, 0x64, 0xcd, 0xc5, 0x01, 0x13, 0x91, 0x60, 0x56, 0x60,
	0xd4, 0xe0, 0x36, 0x92, 0xd7, 0xc3, 0xee, 0xa9, 0x20, 0xa8, 0xb2, 0x20, 0xb8, 0x06, 0x25, 0x2d,
	0x2e, 0x3e, 0x98, 0x5b, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x4b,
	0x93, 0x93, 0x53, 0x8b, 0x8b, 0xc1, 0xce, 0xe3, 0x08, 0x82, 0x71, 0x95, 0xe4, 0xb8, 0x38, 0x60,
	0x26, 0x08, 0x09, 0x71, 0xb1, 0x64, 0x67, 0xe6, 0xc1, 0x7c, 0x00, 0x66, 0x1b, 0x2d, 0x62, 0xe4,
	0x12, 0xf5, 0x4f, 0xce, 0xf4, 0x47, 0x58, 0x1c, 0x0e, 0xb1, 0x58, 0xa8, 0x83, 0x91, 0x8b, 0x0d,
	0x62, 0x8d, 0x90, 0x0a, 0x0e, 0xb7, 0xa1, 0x84, 0x98, 0x94, 0x2a, 0x01, 0x55, 0x10, 0xb7, 0x2a,
	0x19, 0x36, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x5b, 0x49, 0x0d, 0x1c, 0x15, 0x65, 0xc6, 0xfa, 0xf9,
	0xc9, 0x99, 0xba, 0x48, 0xda, 0x74, 0xa1, 0xfa, 0xf4, 0x13, 0xc1, 0xfa, 0xac, 0x18, 0xb5, 0x9c,
	0x24, 0xa3, 0xc4, 0xb1, 0x1a, 0x5d, 0x90, 0x94, 0xc4, 0x06, 0x8e, 0x3f, 0x63, 0x40, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x58, 0x46, 0x60, 0xba, 0x13, 0x02, 0x00, 0x00,
}
